#!/bin/bash

# needed only if you change input.data or input.nn 
#./xscal
#../src/xbuildGh5

# You can run it many times. See xClustering to change clusters number
rm numStructs.csv
#time ../src/xSelectionOnGrid --method=PCA --k=0.9 --scaling=None --p=-4
time ../src/xSelectionOnGrid --method=PCA --k=0.9 --scaling=None --p=-4 --minmax=1
# build new input.data file, named selInput.data
rm selInput.data
../src/xbuildSelectedData
