#!/bin/bash
source /sps/ilm/allouche/Softwares/shell/tensorFlowEnv
SCRIPT=$(readlink -f $0)
export  myDIR=`dirname $SCRIPT`
python $myDIR/Clustering.py --method=HDBSCAN --eps=1e-3 --seed=1 --minsample=2 --p=2.0
