#!/bin/bash
source /sps/ilm/allouche/Softwares/shell/tensorFlowEnv
SCRIPT=$(readlink -f $0)
export  myDIR=`dirname $SCRIPT`
#python $myDIR/Clustering.py --method=DBSCAN --eps=10 --seed=1 --minsample=2 --p=20.0
python $myDIR/Clustering.py --method=DBSCAN --seed=1 --minsample=2 --p=2.0 --eps=-1.0
