#!/bin/bash
source /home/theochem/allouche/shell/tensorFlowEnv
SCRIPT=$(readlink -f $0)
export  myDIR=`dirname $SCRIPT`
#python $myDIR/SelectionOnGrid.py --method=None --scaling=None --p=-2
python $myDIR/SelectionOnGrid.py $@
